### PR TITLE
Deploy to heroku using heroku-buildpack-gradle

### PR DESCRIPTION
**Pull request by tzachz**
Suggested solution for #15: @scruffian - would this do?
Never worked with Heroku before, always wanted to - this worked for me and was rather easy to do (nice work, Heroku!). Please let me know if following the updated README works smoothly :)

### CODE REVIEW

**Comment by scruffian** [comment]
Nice!

It fails when I try to push:

```
remote:        Unzipping /app/tmp/cache/.gradle/wrapper/dists/gradle-2.3-bin/7a1ngj6cc7aafikc3uq95v6rn0/gradle-2.3-bin.zip to /app/tmp/cache/.gradle/wrapper/dists/gradle-2.3-bin/7a1ngj6cc7aafikc3uq95v6rn0
remote:        Set executable permissions for: /app/tmp/cache/.gradle/wrapper/dists/gradle-2.3-bin/7a1ngj6cc7aafikc3uq95v6rn0/gradle-2.3/bin/gradle
remote:        Download https://repo1.maven.org/maven2/eu/appsatori/gradle-fatjar-plugin/0.2/gradle-fatjar-plugin-0.2.pom
remote:        Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.6/groovy-all-2.1.6.pom
remote:        Download https://repo1.maven.org/maven2/eu/appsatori/gradle-fatjar-plugin/0.2/gradle-fatjar-plugin-0.2.jar
remote:        Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.6/groovy-all-2.1.6.jar
remote:        
remote:        FAILURE: Build failed with an exception.
remote:        
remote:        * What went wrong:
remote:        Task 'stage' not found in root project 'build_37a3f3a1e00d1ee6324aee877f7f49d6'.
remote:        
remote:        * Try:
remote:        Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
remote:        
remote:        BUILD FAILED
remote:        
remote:        Total time: 12.459 secs
remote:  !     Failed to build app
remote: 
remote:  !     Push rejected, failed to compile Gradle app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ancient-escarpment-1547.
```

**Comment by tzachz** [comment]
Oh, I think git is trying to push your *master* branch into the remote master, instead of pushing this branch (see [here](http://stackoverflow.com/questions/2971550/how-to-push-different-local-git-branches-to-heroku-master)). Try replacing the push command with: `git push -f heroku HEAD:master`.

**Comment by scruffian** [comment]
Amazing, that works :)

**Comment by ashutoshchauhan13** [comment]
Worked for me....

**Pull request merged**
